import sbt.Def

ThisBuild / scalaVersion := "3.3.5"
ThisBuild / majorVersion := 13
ThisBuild / isPublicArtefact := true
ThisBuild / scalacOptions += "-Wconf:src=src_managed/.*:s" // silence all warnings on autogenerated files

lazy val domain = (project in file("."))
  .settings(publish / skip := true)
  .aggregate(domainPlay30, domainTestPlay30)

lazy val domainPlay30 = Project("domain-play-30", file("domain-play-30"))
  .settings(
    libraryDependencies ++= LibDependencies(),
    scalafmtOnCompile := true
  )
  .settings(ScoverageSettings())

lazy val domainTestPlay30 = Project("domain-test-play-30", file("domain-test-play-30"))
  .settings(
    libraryDependencies ++= LibDependencies(),
    scalafmtOnCompile := true
  )
  .dependsOn(domainPlay30)

//def sharedSources: Seq[Def.Setting[Seq[File]]] = Seq(
//  Compile / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/main/scala",
//  Compile / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/main/resources",
//  Test / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/test/scala",
//  Test / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/test/resources"
//)
