import sbt.Def

ThisBuild / scalaVersion := "3.3.5"
ThisBuild / majorVersion := 12
ThisBuild / isPublicArtefact := true
ThisBuild / scalacOptions += "-Wconf:src=src_managed/.*:s" // silence all warnings on autogenerated files

lazy val domain = (project in file("."))
  .settings(publish / skip := true)
  .aggregate(play30)

lazy val play30 = Project("domain-play-30", file("play-30"))
  .settings(
    libraryDependencies ++= LibDependencies(),
    scalafmtOnCompile := true,
    sharedSources
  )
  .settings(ScoverageSettings())

def sharedSources: Seq[Def.Setting[Seq[File]]] = Seq(
  Compile / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/main/scala",
  Compile / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/main/resources",
  Test / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/test/scala",
  Test / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/test/resources"
)
