
ThisBuild / scalaVersion       := "3.3.4"
ThisBuild / majorVersion       := 12
ThisBuild / isPublicArtefact   := true
ThisBuild / scalacOptions      += "-Wconf:src=src_managed/.*:s" // silence all warnings on autogenerated files

lazy val domain = (project in file("."))
  .settings(publish / skip := true)
  .aggregate(play30)

lazy val commonSettings =
  ScalariformSettings() ++ ScoverageSettings()

lazy val play30 = Project("domain-play-30", file("play-30"))
  .settings(
    libraryDependencies ++= LibDependencies(),
    sharedSources
  )
  .settings(commonSettings)

def sharedSources = Seq(
  Compile / unmanagedSourceDirectories   += baseDirectory.value / "../shared/src/main/scala",
  Compile / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/main/resources",
  Test    / unmanagedSourceDirectories   += baseDirectory.value / "../shared/src/test/scala",
  Test    / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/test/resources"
)
